### PR TITLE
Update iis dependency to 2.x

### PR DESCRIPTION
**Pull request by npwalker**
puppet/iis shipped a 2.0.0 version in February

https://forge.puppetlabs.com/puppet/iis

### CODE REVIEW

**Comment by ferventcoder** [comment]
I'd like a chance to review the features first - but other than that 👍

**Comment by ferventcoder** [comment]
Reviewed, looks sweet!

**Comment by ferventcoder** [comment]
@puppetlabs/windows Please provide feedback by COB - this will merge tomorrow if no one has any issues.

**Comment by jpogran** [comment]
👍

**Comment by ferventcoder** [comment]
Thanks for the contribution!

**Pull request merged**
